included:
  - Sources/Userpilot
  - Tests/UserpilotTests

excluded:
  - .build
  - DerivedData
  - .swiftpm
  - checkouts
  - SourcePackages
  - Dependencies
  - Sources/Userpilot/Vendor
  - Tests/UserpilotTests/Vendor

