//
//  Storage.swift
//  UserPilot SDK
//
//  Created by Motasem Hamed on 18/08/2024.
//  Copyright © 2024 UserPilot. All rights reserved.
//
//  [Brief Description]
//  The `Storage` class provides a mechanism for storing and caching runtime data, including 
//  settings like the socket URL, device ID, and user ID. It uses `UserDefaults` to persist data across app sessions.
//

import Foundation
import UIKit

/**
 Protocol that defines the methods and properties required for data storage in the UserPilot SDK.

 - Properties:
   - `socketURL`: The URL for the socket connection.
   - `deviceID`: A unique identifier for the device, generated on the first initialization of the SDK.
   - `userID`: The current user’s ID, which may be an anonymous or authenticated value.
   - `user`: The current user, which contains all user details.
 */
internal protocol DataStoring: AnyObject {
    /// The socket URL used to connect the SDK to the backend services.
    var socketURL: String { get set }

    /// A unique identifier for the device, generated during the SDK's first initialization.
    var deviceID: String { get set }

    /// The current user ID, which could be either a generated anonymous ID or a value provided
    ///  by the application upon authentication.
    var userID: String { get set }

    /// The socket URL used to connect the SDK to the backend services.
    var user: String { get set }

    /// The socket URL used to connect the SDK to the backend services.
    var imagesCache: [NSString: Date] { get set }
}

/**
 The `Storage` class implements the `DataStoring` protocol and manages runtime data persistence for the SDK.

 It utilizes `UserDefaults` to store data that should persist between app sessions, such as the
 socket URL, device ID, and user ID. The class ensures that data is retrieved efficiently and updated when necessary.
 */
internal class Storage: DataStoring {

    // MARK: - Keys

    /**
     An enum that defines the keys used to store data in `UserDefaults`.

     These keys correspond to the properties being stored, ensuring a consistent mapping between
     runtime properties and their storage keys.
     */
    private enum Key: String {
        case socketURL
        case deviceID
        case userID
        case user
        case isAnonymous
        case imagesCache
    }

    // MARK: - Properties

    /// The configuration object for the UserPilot SDK, containing settings that are resolved via dependency injection.
    private let config: UserPilot.Config

    /// A lazy-loaded `UserDefaults` instance, scoped to the SDK’s user defaults suite name for isolating stored data.
    private lazy var defaults = UserDefaults(
        suiteName: "\(Storage.userDefaultSuiteName)\(Bundle.main.identifier)"
    )

    /// The URL of the socket connection used by the SDK. The value is stored and retrieved from `UserDefaults`.
    internal var socketURL: String {
        get {
            return read(.socketURL, defaultValue: "")
        }
        set {
            write(.socketURL, newValue: newValue)
        }
    }

    /// The unique device identifier, generated when the SDK is initialized for the first time. The value
    ///  is cached for subsequent access.
    internal var deviceID: String {
        get {
            return read(.deviceID, defaultValue: "")
        }
        set {
            write(.deviceID, newValue: newValue)
        }
    }

    /// The user ID, which could be an anonymous ID generated by the SDK or an authenticated ID provided by
    ///  the app.
    internal var userID: String {
        get {
            return read(.userID, defaultValue: "")
        }
        set {
            write(.userID, newValue: newValue)
        }
    }

    /// The user, which contains all updated user meta data and company.
    internal var user: String {
        get {
            return read(.user, defaultValue: User().toJson() ?? "")
        }
        set {
            write(.user, newValue: newValue)
        }
    }

    /// The user, which contains all updated user meta data and company.
    internal var imagesCache: [NSString: Date] {
        get {
            return read(.imagesCache, defaultValue: [:])
        }
        set {
            write(.imagesCache, newValue: newValue)
        }
    }

    // MARK: - Initialization

    /**
     Initializes the `Storage` object with a dependency injection container.

     - Parameter container: The DI container used to resolve dependencies, including the SDK's `Config` object.
     */
    init(container: DIContainer) {
        self.config = container.resolve(UserPilot.Config.self)
        self.deviceID = UIDevice.identifier // Generate and assign the device identifier.
    }

    // MARK: - Helper Methods

    /**
     Reads a value from `UserDefaults` for a given key. If the key is not present in `UserDefaults`,
     a default value is returned.

     - Parameters:
       - key: The key associated with the value to read.
       - defaultValue: The default value to return if the key is not present in `UserDefaults`.
     - Returns: The value associated with the key, or the default value if the key does not exist.
     */
    private func read<T>(_ key: Key, defaultValue: T) -> T {
        return defaults?.object(forKey: key.rawValue) as? T ?? defaultValue
    }

    /**
     Writes a value to `UserDefaults` for a given key. If the value is `nil`, the key is removed from `UserDefaults`.

     - Parameters:
       - key: The key under which to store the value.
       - newValue: The value to store. If `nil`, the key is removed from `UserDefaults`.
     */
    private func write<T>(_ key: Key, newValue: T?) {
        guard let newValue = newValue else {
            defaults?.removeObject(forKey: key.rawValue)
            return
        }

        defaults?.set(newValue, forKey: key.rawValue)
    }
}

// MARK: - Properties name

internal extension Storage {

    // Static constants
    static let userDefaultSuiteName = "com.userpilot.storage."
}
