//
//  Storage.swift
//  Userpilot SDK
//
//  Created by Userpilot on 18/08/2024.
//  Copyright © 2024 Userpilot. All rights reserved.
//
//  The `Storage` class provides a mechanism for storing and caching runtime data, including
//  settings like the socket URL, pending identify, and user ID across app sessions using `UserDefaults`.
//

import Foundation
import UIKit

/// Per-tenant identity, pending identify, and infrastructure values retained across launches.
internal protocol DataStoring: AnyObject {
    /// The socket URL used to connect the SDK to the backend services.
    var socketURL: String { get set }

    /// The current user ID, which could be either a generated anonymous Id or a value provided
    ///  by the application upon authentication.
    var userId: String { get set }

    /// The anonymous user ID, generated by SDK.
    var anonymousUserId: String { get set }

    /// The pending identify payload retained until acknowledgement or offline restoration.
    var temporaryUser: String? { get set }

    /// The date for session when app enter background state.
    var sessionDate: Date? { get set }

    /// The date for configuration to update it.
    var configurationDate: Date? { get set }

    /// Push token for APNs
    var pushToken: String? { get set }
}

/**
 The `Storage` class implements the `DataStoring` protocol and manages runtime data persistence for the SDK.

 It utilizes `UserDefaults` to store data that should persist between app sessions, such as the
 socket URL, pending identify, and user ID. Each configured token uses its own suite.
 */
internal class Storage: DataStoring {
    // MARK: - Keys

    /**
     An enum that defines the keys used to store data in `UserDefaults`.

     These keys correspond to the properties being stored, ensuring a consistent mapping between
     runtime properties and their storage keys.
     */
    internal enum Key: String, CaseIterable {
        case socketURL
        case userId
        case anonymousUserId
        case temporaryUser
        case sessionDate
        case configurationDate
        case pushToken
    }

    // MARK: - Properties

    /// Immutable suite reference shared by SDK services. UserDefaults synchronizes individual accesses;
    /// callers continue to own ordering for multi-field identity and session transitions.
    private let defaults: UserDefaults?

    /// The URL of the socket connection used by the SDK. The value is stored and retrieved from `UserDefaults`.
    internal var socketURL: String {
        get {
            return read(.socketURL, defaultValue: "")
        }
        set {
            write(.socketURL, newValue: newValue)
        }
    }

    /// The user ID, which could be an anonymous Id generated by the SDK or an authenticated Id provided by
    ///  the app.
    internal var userId: String {
        get {
            return read(.userId, defaultValue: "")
        }
        set {
            write(.userId, newValue: newValue)
        }
    }

    /// The anonymous user ID, which generated by the SDK.
    internal var anonymousUserId: String {
        get {
            return read(.anonymousUserId, defaultValue: "")
        }
        set {
            write(.anonymousUserId, newValue: newValue)
        }
    }

    /// Pending identify payload; JSON remains available for offline restoration.
    internal var temporaryUser: String? {
        get {
            return read(.temporaryUser, defaultValue: nil)
        }
        set {
            write(.temporaryUser, newValue: newValue)
        }
    }

    /// The session Date, which used for tracking app background duration.
    internal var sessionDate: Date? {
        get {
            return read(.sessionDate, defaultValue: nil)
        }
        set {
            write(.sessionDate, newValue: newValue)
        }
    }

    /// The session Date, which used for update configuration.
    internal var configurationDate: Date? {
        get {
            return read(.configurationDate, defaultValue: nil)
        }
        set {
            write(.configurationDate, newValue: newValue)
        }
    }

    internal var pushToken: String? {
        get {
            return read(.pushToken, defaultValue: nil)
        }
        set {
            write(.pushToken, newValue: newValue)
        }
    }

    // MARK: - Initialization

    /**
     Initializes the `Storage` object with a dependency injection container.

     - Parameter container: The DI container used to resolve dependencies, including the SDK's `Config` object.
     */
    init(container: DIContainer) {
        let config = container.resolve(Userpilot.Config.self)
        defaults = UserDefaults(suiteName: Storage.suiteName(forToken: config.token))
        // Migration has already run. Only the obsolete merged profile is discarded;
        // live identity and pending identify data keep their existing keys and values.
        defaults?.removeObject(forKey: Storage.legacyUserKey)
        sessionDate = nil
    }

    // MARK: - Helper Methods

    /**
     Reads a value from `UserDefaults` for a given key. If the key is not present in `UserDefaults`,
     a default value is returned.

     - Parameters:
       - key: The key associated with the value to read.
       - defaultValue: The default value to return if the key is not present in `UserDefaults`.
     - Returns: The value associated with the key, or the default value if the key does not exist.
     */
    private func read<T>(_ key: Key, defaultValue: T) -> T {
        return defaults?.object(forKey: key.rawValue) as? T ?? defaultValue
    }

    /**
     Writes a value to `UserDefaults` for a given key. If the value is `nil`, the key is removed from `UserDefaults`.

     - Parameters:
       - key: The key under which to store the value.
       - newValue: The value to store. If `nil`, the key is removed from `UserDefaults`.
     */
    private func write<T>(_ key: Key, newValue: T?) {
        guard let defaults else { return }

        if let newValue {
            defaults.set(newValue, forKey: key.rawValue)
        } else {
            defaults.removeObject(forKey: key.rawValue)
        }

        defaults.synchronize()
    }
}

// MARK: - Properties name

internal extension Storage {

    // Static constants

    /// Retained only to remove the obsolete merged profile and recognize populated legacy suites.
    static let legacyUserKey = "user"

    /// Prefix for `UserDefaults` suite names. Combined with the host app's bundle
    /// identifier and the SDK token to form the full suite, e.g.
    /// `com.userpilot.storage.com.acme.app.MY_TOKEN`.
    static let userDefaultSuiteName = "com.userpilot.storage."

    /// Legacy suite name used by SDK v1 (no token component).
    /// Retained for one-shot migration only — never written to from v2.
    static var legacyUserDefaultSuiteName: String {
        return "\(userDefaultSuiteName)\(Bundle.main.identifier)"
    }

    /// Process-shared `UserDefaults` suite that records cross-tenant migration
    /// facts (currently just the first token that absorbed legacy data). Used
    /// by `StorageMigrator` to enforce a first-token-wins policy across
    /// `Userpilot` instances coexisting in the same process.
    static let legacySystemSuiteName = "\(userDefaultSuiteName)__system"

    /// Builds the per-tenant `UserDefaults` suite name for `token`.
    static func suiteName(forToken token: String) -> String {
        return "\(userDefaultSuiteName)\(Bundle.main.identifier).\(token)"
    }
}
